package encode

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/mjnitz02/media-compressor/internal/decide"
	"github.com/mjnitz02/media-compressor/internal/probe"
)

// Every test here works on clips generated by ffmpeg itself -- two seconds of
// testsrc and a sine wave -- never on anything from a real library. A test
// that needed a film to run is a test nobody runs.

func requireFFmpeg(t *testing.T) {
	t.Helper()
	for _, bin := range []string{"ffmpeg", "ffprobe"} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Skipf("%s is not installed", bin)
		}
	}
}

// makeClip writes a short clip with one video stream and one audio stream per
// entry in languages ("" for an untagged track).
//
// The video is encoded losslessly so that a re-encode of it is genuinely
// smaller, the way a real file's would be. testsrc compresses so well that a
// lossy source would already be at the floor.
func makeClip(t *testing.T, path string, languages ...string) {
	t.Helper()
	if len(languages) == 0 {
		languages = []string{"eng"}
	}

	args := []string{
		"-hide_banner", "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "testsrc=size=320x240:rate=15:duration=2",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=2",
		"-map", "0:v",
	}
	for range languages {
		args = append(args, "-map", "1:a")
	}
	args = append(args, "-c:v", "libx264", "-qp", "0", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest")
	for i, lang := range languages {
		if lang != "" {
			args = append(args, fmt.Sprintf("-metadata:s:a:%d", i), "language="+lang)
		}
	}
	args = append(args, path)

	out, err := exec.Command("ffmpeg", args...).CombinedOutput()
	if err != nil {
		t.Fatalf("generating %s: %v\n%s", path, err, out)
	}
}

func probeFile(t *testing.T, path string) *probe.Result {
	t.Helper()
	r, err := probe.Prober{}.Run(context.Background(), path)
	if err != nil {
		t.Fatalf("probing %s: %v", path, err)
	}
	return r
}

// remuxProfile keeps English audio only, so a clip with an eng and an fra
// track needs exactly one stream dropped and no re-encode.
func remuxProfile() decide.Profile {
	p := decide.Standard()
	p.Audio.KeepLanguages = []string{"eng"}
	return p
}

// encodeProfile re-encodes with libx265, which is available wherever ffmpeg
// is. The floor is dropped to zero because a two-second clip is nowhere near
// 3000 kbps and the point here is the mechanics, not the quality rule --
// which has its own 1,881-file corpus in internal/decide.
func encodeProfile() decide.Profile {
	p := decide.Standard()
	p.Video.Encoder = "libx265"
	p.Video.Bitrate.FloorKbps = 0
	return p
}

func plan(t *testing.T, path string, p decide.Profile) (*probe.Result, decide.Plan) {
	t.Helper()
	r := probeFile(t, path)
	return r, decide.Decide(r, p)
}

func mustRun(t *testing.T, e Encoder, r *probe.Result, pl decide.Plan) *Result {
	t.Helper()
	job, err := e.Prepare(r, pl)
	if err != nil {
		t.Fatalf("Prepare: %v", err)
	}
	res, err := e.Run(context.Background(), job)
	if err != nil {
		t.Fatalf("Run: %v\nffmpeg said: %s", err, res.FFmpegOutput)
	}
	return res
}

func TestRemuxReplacesTheFileInPlace(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Some Film (1982).mkv")
	makeClip(t, src, "eng", "fra")

	before := probeFile(t, src)
	r, pl := plan(t, src, remuxProfile())
	if pl.Action != decide.ActionRemux {
		t.Fatalf("action = %s, want remux (plan: %+v)", pl.Action, pl)
	}

	res := mustRun(t, Encoder{}, r, pl)
	if !res.Replaced {
		t.Fatal("the file was not replaced")
	}

	// Same directory, same name. This is the whole safety story.
	after := probeFile(t, src)
	if len(after.StreamsOfType(probe.TypeAudio)) != 1 {
		t.Errorf("audio streams = %d, want 1 (the fra track dropped)",
			len(after.StreamsOfType(probe.TypeAudio)))
	}
	if got := len(before.StreamsOfType(probe.TypeAudio)); got != 2 {
		t.Fatalf("the fixture should have started with 2 audio streams, had %d", got)
	}
	if res.TempKept != "" {
		t.Errorf("a successful run should leave no temp file, got %s", res.TempKept)
	}
	assertNoLeftovers(t, dir, filepath.Base(src))
}

func TestEncodeProducesTheTargetCodec(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng")

	r, pl := plan(t, src, encodeProfile())
	if pl.Action != decide.ActionEncode {
		t.Fatalf("action = %s, want encode; reason %q", pl.Action, pl.Reason)
	}

	res := mustRun(t, Encoder{}, r, pl)
	if !res.Replaced {
		t.Fatal("the file was not replaced")
	}
	if v := res.Verification; !strings.EqualFold(v.VideoCodec, "hevc") {
		t.Errorf("output codec = %s, want hevc", v.VideoCodec)
	}
	if res.Verification.OutputSize >= res.Verification.SourceSize {
		t.Errorf("the encode should have shrunk the file: %d from %d",
			res.Verification.OutputSize, res.Verification.SourceSize)
	}
	assertNoLeftovers(t, dir, "Film.mkv")
}

// The one rename this tool performs: same directory, same base name, new
// extension. The original has to be gone afterwards, and only afterwards.
func TestForcingAContainerRenamesAndRemovesTheOriginal(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mp4")
	makeClip(t, src, "eng")

	p := remuxProfile()
	p.Container = decide.ContainerMKV
	r, pl := plan(t, src, p)
	if !pl.ExtensionChanges() {
		t.Fatalf("expected an extension change, got container %s from %s", pl.Container, pl.SourceContainer)
	}

	res := mustRun(t, Encoder{}, r, pl)
	if !res.SourceRemoved {
		t.Error("the original should have been removed after the replacement landed")
	}
	if _, err := os.Stat(src); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("%s should be gone, stat gave %v", src, err)
	}
	if _, err := os.Stat(filepath.Join(dir, "Film.mkv")); err != nil {
		t.Errorf("Film.mkv should exist: %v", err)
	}
	assertNoLeftovers(t, dir, "Film.mkv")
}

// Converting Film.mp4 to Film.mkv when a Film.mkv already exists would
// destroy that file, and it belongs to somebody.
func TestARenameThatWouldOverwriteAnExistingFileIsRefused(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mp4")
	makeClip(t, src, "eng")
	existing := filepath.Join(dir, "Film.mkv")
	if err := os.WriteFile(existing, []byte("someone else's file"), 0o644); err != nil {
		t.Fatal(err)
	}

	p := remuxProfile()
	p.Container = decide.ContainerMKV
	r, pl := plan(t, src, p)

	if _, err := (Encoder{}).Prepare(r, pl); err == nil {
		t.Fatal("Prepare should refuse to overwrite an existing file")
	} else if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("want a clear reason, got %v", err)
	}

	if data, _ := os.ReadFile(existing); string(data) != "someone else's file" {
		t.Error("the existing file was touched")
	}
}

// Replacing a symlink in place would leave a regular file at this path and
// orphan the real file wherever it lives -- a quiet reorganisation of the
// library, which is the thing this tool must never do.
func TestASymlinkIsRefused(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	real := filepath.Join(dir, "real", "Film.mkv")
	if err := os.MkdirAll(filepath.Dir(real), 0o755); err != nil {
		t.Fatal(err)
	}
	makeClip(t, real, "eng", "fra")

	link := filepath.Join(dir, "Film.mkv")
	if err := os.Symlink(real, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	r := probeFile(t, link)
	pl := decide.Decide(r, remuxProfile())
	_, err := (Encoder{}).Prepare(r, pl)
	if err == nil {
		t.Fatal("Prepare should refuse a symlink")
	}
	if !strings.Contains(err.Error(), "symlink") {
		t.Errorf("want the reason to say symlink, got %v", err)
	}
}

// A verification failure must leave the original byte-for-byte as it was, and
// keep the output so it can be looked at.
func TestAFailedVerificationLeavesTheOriginalAloneAndKeepsTheOutput(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng")

	original, err := os.ReadFile(src)
	if err != nil {
		t.Fatal(err)
	}

	r, pl := plan(t, src, remuxProfile())
	// -t truncates the output to half a second, which is exactly the shape of
	// a real failure: ffmpeg exits 0 and writes a perfectly valid file that
	// happens not to be the film.
	pl.OutputArgs = append([]string{"-t", "0.5"}, pl.OutputArgs...)
	pl.Action = decide.ActionRemux

	e := Encoder{}
	job, err := e.Prepare(r, pl)
	if err != nil {
		t.Fatal(err)
	}
	res, err := e.Run(context.Background(), job)
	if err == nil {
		t.Fatal("a truncated output must not be accepted")
	}
	if res.Replaced {
		t.Fatal("the file was replaced despite failing verification")
	}

	now, readErr := os.ReadFile(src)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(now) != string(original) {
		t.Error("the original was modified")
	}
	if res.TempKept == "" {
		t.Fatal("the failed output should have been kept for inspection")
	}
	if _, err := os.Stat(res.TempKept); err != nil {
		t.Errorf("the kept output is not there: %v", err)
	}
	if !strings.Contains(err.Error(), "apart") {
		t.Errorf("the error should say what was wrong, got %v", err)
	}
}

// An *arr stack upgrading the source while it is being encoded would
// otherwise have its new file silently overwritten by a re-encode of the old
// one. The fake ffmpeg here disturbs the source exactly the way that would.
func TestASourceThatChangesDuringTheEncodeIsNotReplaced(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng", "fra")

	// A valid output for the fake ffmpeg to produce, so that the run gets
	// past verification and fails on the source check specifically.
	good := filepath.Join(t.TempDir(), "good.mkv")
	makeClip(t, good, "eng")

	fake := filepath.Join(t.TempDir(), "ffmpeg")
	script := "#!/bin/sh\n" +
		"out=\"\"; src=\"\"; prev=\"\"\n" +
		"for a in \"$@\"; do\n" +
		"  if [ \"$prev\" = \"-i\" ]; then src=\"$a\"; fi\n" +
		"  out=\"$a\"; prev=\"$a\"\n" +
		"done\n" +
		"cp \"$GOOD_OUTPUT\" \"$out\"\n" +
		"printf 'upgraded' >> \"$src\"\n"
	if err := os.WriteFile(fake, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("GOOD_OUTPUT", good)

	r, pl := plan(t, src, remuxProfile())
	e := Encoder{Binary: fake}
	job, err := e.Prepare(r, pl)
	if err != nil {
		t.Fatal(err)
	}
	res, err := e.Run(context.Background(), job)
	if err == nil {
		t.Fatal("the replace should have been abandoned")
	}
	if res.Replaced {
		t.Fatal("the upgraded source was overwritten")
	}
	if !strings.Contains(err.Error(), "changed while it was being encoded") {
		t.Errorf("want a clear reason, got %v", err)
	}
	if !strings.HasSuffix(mustRead(t, src), "upgraded") {
		t.Error("the source no longer holds what the other process wrote")
	}
	if res.TempKept == "" {
		t.Error("the output should have been kept")
	}
}

// A rename gives the new file the temp's mode, which is this process's
// umask, not the library's. On a share read by Plex, the *arr stacks and SMB
// alike, a file that turns up as 0600 is a support call.
func TestTheReplacementKeepsTheOriginalsPermissions(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng", "fra")
	if err := os.Chmod(src, 0o640); err != nil {
		t.Fatal(err)
	}

	r, pl := plan(t, src, remuxProfile())
	mustRun(t, Encoder{}, r, pl)

	info, err := os.Stat(src)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0o640 {
		t.Errorf("mode = %v, want 0640", got)
	}
}

func TestNothingIsWrittenUntilRunIsCalled(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng", "fra")

	r, pl := plan(t, src, remuxProfile())
	job, err := (Encoder{}).Prepare(r, pl)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(job.TempPath); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("Prepare created %s; it must touch nothing", job.TempPath)
	}
	assertNoLeftovers(t, dir, "Film.mkv")
}

func TestPrepareDeclinesAPlanWithNoWork(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng")

	p := remuxProfile()
	p.Audio.TagUntaggedAs = ""
	p.Strip.DataStreams = false
	p.Strip.CoverArt = false
	p.Video.LeaveAlone = []string{"h264", "hevc", "av1"}

	r, pl := plan(t, src, p)
	if pl.Action != decide.ActionNone {
		t.Fatalf("action = %s, want none: %+v", pl.Action, pl)
	}
	if _, err := (Encoder{}).Prepare(r, pl); !errors.Is(err, ErrNothingToDo) {
		t.Errorf("err = %v, want ErrNothingToDo", err)
	}
}

// mustRead returns a file's contents as a string.
func mustRead(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// assertNoLeftovers checks the directory holds only the files named. A temp
// file left in a media folder would be picked up by the next scan.
func assertNoLeftovers(t *testing.T, dir string, want ...string) {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	allowed := map[string]bool{}
	for _, w := range want {
		allowed[w] = true
	}
	for _, e := range entries {
		if !allowed[e.Name()] {
			t.Errorf("%s left behind in %s", e.Name(), dir)
		}
	}
}

// ffmpeg failing outright is the easy case, but it still has to leave the
// original alone and say what went wrong.
func TestAnFFmpegFailureLeavesTheOriginalAlone(t *testing.T) {
	requireFFmpeg(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	makeClip(t, src, "eng", "fra")
	original := mustRead(t, src)

	r, pl := plan(t, src, remuxProfile())
	// A codec that does not exist. ffmpeg exits non-zero and says so. It goes
	// at the end because ffmpeg takes the last -c:v it is given.
	pl.OutputArgs = append(pl.OutputArgs, "-c:v", "no_such_encoder")

	e := Encoder{}
	job, err := e.Prepare(r, pl)
	if err != nil {
		t.Fatal(err)
	}
	res, err := e.Run(context.Background(), job)
	if err == nil {
		t.Fatal("a failed ffmpeg run must be an error")
	}
	if res.Replaced {
		t.Fatal("the file was replaced despite ffmpeg failing")
	}
	if mustRead(t, src) != original {
		t.Error("the original was modified")
	}
	if !strings.Contains(err.Error(), "no_such_encoder") {
		t.Errorf("the error should carry ffmpeg's own message, got %v", err)
	}
}

// Ctrl-C or a container stop is not a failure worth preserving evidence of,
// and a partial file left behind on every restart would litter the library.
func TestACancelledEncodeCleansUpItsTempFile(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "Film.mkv")
	requireFFmpeg(t)
	makeClip(t, src, "eng", "fra")

	// A fake ffmpeg that creates the temp file and then does not finish, so
	// the cancellation lands mid-encode.
	fake := filepath.Join(t.TempDir(), "ffmpeg")
	script := "#!/bin/sh\n" +
		"for a in \"$@\"; do out=\"$a\"; done\n" +
		"printf partial > \"$out\"\n" +
		// exec so that the process the encoder kills is the one that is
		// holding the pipe open, as ffmpeg itself would be.
		"exec sleep 30\n"
	if err := os.WriteFile(fake, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}

	r, pl := plan(t, src, remuxProfile())
	e := Encoder{Binary: fake}
	job, err := e.Prepare(r, pl)
	if err != nil {
		t.Fatal(err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		// Wait for the fake to have written its partial file, then stop it.
		for i := 0; i < 200; i++ {
			if _, err := os.Stat(job.TempPath); err == nil {
				break
			}
			time.Sleep(10 * time.Millisecond)
		}
		cancel()
	}()

	res, err := e.Run(ctx, job)
	if err == nil {
		t.Fatal("a cancelled run must be an error")
	}
	if res.Replaced {
		t.Fatal("the file was replaced")
	}
	if _, err := os.Stat(job.TempPath); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("the partial file should have been cleaned up, stat gave %v", err)
	}
	if res.TempKept != "" {
		t.Errorf("nothing should be kept for inspection after a cancellation, got %s", res.TempKept)
	}
	assertNoLeftovers(t, dir, "Film.mkv")
}

// The dry-run output has to be a command you can paste, which means the
// quoting has to survive the punctuation real media filenames are full of.
func TestCommandQuotesAwkwardFilenames(t *testing.T) {
	j := &Job{Args: []string{"-i", "/mnt/movies/Amélie (2001) [1080p].mkv", "-c:v", "copy", "/tmp/out.mkv"}}
	got := j.Command("ffmpeg")

	if !strings.Contains(got, `'/mnt/movies/Amélie (2001) [1080p].mkv'`) {
		t.Errorf("a name with spaces and brackets must be quoted: %s", got)
	}
	// Plain tokens are left alone, so the command stays readable.
	if !strings.Contains(got, "ffmpeg -i ") || !strings.Contains(got, " -c:v copy ") {
		t.Errorf("plain arguments should not be quoted: %s", got)
	}

	j = &Job{Args: []string{"/mnt/movies/Rock 'n' Roll.mkv"}}
	if got := j.Command(""); !strings.Contains(got, `'/mnt/movies/Rock '\''n'\'' Roll.mkv'`) {
		t.Errorf("apostrophes must be escaped: %s", got)
	}
}
