package runner

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/mjnitz02/media-compressor/internal/decide"
	"github.com/mjnitz02/media-compressor/internal/encode"
	"github.com/mjnitz02/media-compressor/internal/probe"
	"github.com/mjnitz02/media-compressor/internal/queue"
	"github.com/mjnitz02/media-compressor/internal/scan"
	"github.com/mjnitz02/media-compressor/internal/store"
)

// Everything here runs against clips generated by ffmpeg -- two seconds of
// testsrc and a sine wave -- never against anything from a real library.

const minAge = time.Hour

func requireFFmpeg(t *testing.T) {
	t.Helper()
	for _, bin := range []string{"ffmpeg", "ffprobe"} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Skipf("%s is not installed", bin)
		}
	}
}

// makeClip writes a short clip in codec ("libx264" or "libx265") with one
// audio track per language ("" for untagged).
func makeClip(t *testing.T, path, codec string, languages ...string) {
	t.Helper()
	args := []string{
		"-hide_banner", "-loglevel", "error", "-y",
		"-f", "lavfi", "-i", "testsrc=size=320x240:rate=15:duration=2",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=2",
		"-map", "0:v",
	}
	for range languages {
		args = append(args, "-map", "1:a")
	}
	args = append(args, "-c:v", codec, "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest")
	if codec == "libx264" {
		// Lossless, so that a re-encode of it is genuinely smaller the way a
		// real file's would be.
		args = append(args, "-qp", "0")
	} else {
		args = append(args, "-x265-params", "log-level=none")
	}
	for i, lang := range languages {
		if lang != "" {
			args = append(args, fmt.Sprintf("-metadata:s:a:%d", i), "language="+lang)
		}
	}
	args = append(args, path)

	if out, err := exec.Command("ffmpeg", args...).CombinedOutput(); err != nil {
		t.Fatalf("generating %s: %v\n%s", path, err, out)
	}
}

// script writes an executable shell script and returns its path.
func script(t *testing.T, name, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte("#!/bin/sh\n"+body), 0o755); err != nil {
		t.Fatalf("writing %s: %v", name, err)
	}
	return path
}

// harness is one library directory, one database and a runner over both, with
// a clock the test moves by hand so that settling does not need real waiting.
type harness struct {
	t       *testing.T
	dir     string
	store   *store.Store
	runner  *Runner
	profile decide.Profile
	now     time.Time
	counter string
}

func newHarness(t *testing.T) *harness {
	t.Helper()
	requireFFmpeg(t)

	dir := t.TempDir()
	db, err := store.Open(filepath.Join(t.TempDir(), "state.db"))
	if err != nil {
		t.Fatalf("store.Open: %v", err)
	}
	t.Cleanup(func() { db.Close() })

	// A counting wrapper around ffprobe, so a test can assert that a settled
	// library is not re-probed. That claim is the entire justification for
	// the decision cache, and it is not observable any other way.
	counter := filepath.Join(t.TempDir(), "probes")
	real, err := exec.LookPath("ffprobe")
	if err != nil {
		t.Skip("ffprobe is not installed")
	}
	counting := script(t, "ffprobe-counting",
		"echo . >> "+strconv.Quote(counter)+"\nexec "+real+" \"$@\"\n")

	h := &harness{
		t:       t,
		dir:     dir,
		store:   db,
		profile: keepEnglishOnly(),
		now:     time.Now(),
		counter: counter,
	}
	h.runner = &Runner{
		Store:  db,
		Prober: probe.Prober{Binary: counting},
		// The encoder gets a plain prober: its verification pass would
		// otherwise be counted as scanning work.
		Encoder: encode.Encoder{Prober: probe.Prober{}},
		Scan:    scan.Options{Extensions: []string{"mkv", "mp4"}, MinAge: minAge},
	}
	return h
}

// keepEnglishOnly drops non-English audio, so a clip with an eng and an fra
// track needs exactly one stream dropped.
func keepEnglishOnly() decide.Profile {
	p := decide.Standard()
	p.Audio.KeepLanguages = []string{"eng"}
	return p
}

func (h *harness) path(name string) string { return filepath.Join(h.dir, name) }

func (h *harness) advance(d time.Duration) { h.now = h.now.Add(d) }

func (h *harness) probeCount() int {
	b, err := os.ReadFile(h.counter)
	if os.IsNotExist(err) {
		return 0
	}
	if err != nil {
		h.t.Fatalf("reading the probe counter: %v", err)
	}
	return strings.Count(string(b), ".")
}

func (h *harness) resetProbeCount() {
	if err := os.Remove(h.counter); err != nil && !os.IsNotExist(err) {
		h.t.Fatalf("resetting the probe counter: %v", err)
	}
}

func (h *harness) target() Target {
	return Target{Label: "library movies", Library: "movies", Roots: []string{h.dir}, Profile: h.profile}
}

func (h *harness) pass(o Options) *Summary {
	h.t.Helper()
	h.runner.Scan.Now = h.now
	h.runner.Now = func() time.Time { return h.now }
	h.runner.Encoder.Prober = probe.Prober{}
	if o.Workers == (queue.Workers{}) {
		o.Workers = queue.Workers{Remux: 2, Encode: 1}
	}
	if o.ProbeWorkers == 0 {
		o.ProbeWorkers = 2
	}
	sum, err := h.runner.Pass(context.Background(), h.target(), o)
	if err != nil {
		h.t.Fatalf("Pass(%s): %v", o.Mode, err)
	}
	return sum
}

// settle runs the two scans a file needs before it is eligible, leaving the
// clock past the grace period.
func (h *harness) settle() {
	h.t.Helper()
	h.advance(2 * minAge)
	h.pass(Options{Mode: ModeScan})
	h.advance(2 * minAge)
}

func (s *Summary) find(t *testing.T, name string) Outcome {
	t.Helper()
	for _, o := range s.Outcomes {
		if filepath.Base(o.Path) == name {
			return o
		}
	}
	t.Fatalf("%s is not in the summary (%d outcomes)", name, len(s.Outcomes))
	return Outcome{}
}

func TestPlanWritesNothingAnywhere(t *testing.T) {
	h := newHarness(t)
	src := h.path("Some Film (1982).mkv")
	makeClip(t, src, "libx264", "eng", "fra")

	before, err := os.Stat(src)
	if err != nil {
		t.Fatal(err)
	}

	h.advance(2 * minAge)
	sum := h.pass(Options{Mode: ModePlan})

	out := sum.find(t, "Some Film (1982).mkv")
	if out.Job == nil {
		t.Fatal("plan did not work out the job; a dry run is meant to print the real one")
	}
	// A dry run is the real code path stopped one step short, so the file is
	// planned in full and reported as not eligible yet -- rather than hidden,
	// which would make plan on a fresh database look like an empty library.
	if out.Waiting == "" {
		t.Error("want the plan to say this file is not eligible yet")
	}

	after, err := os.Stat(src)
	if err != nil {
		t.Fatal(err)
	}
	if after.Size() != before.Size() || !after.ModTime().Equal(before.ModTime()) {
		t.Error("plan modified the file")
	}

	// And nothing was remembered either: a plan that recorded sightings would
	// make `run` behave differently depending on whether you ran `plan` first.
	states, err := h.store.Lookup(context.Background(), []string{src})
	if err != nil {
		t.Fatal(err)
	}
	if len(states) != 0 {
		t.Error("plan wrote a row to the database")
	}
	c, err := h.store.Counts(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if c.Files != 0 || c.Decided != 0 {
		t.Errorf("plan left %+v in the database", c)
	}
}

func TestAFileIsNotTouchedUntilASecondScanFindsItUnchanged(t *testing.T) {
	h := newHarness(t)
	src := h.path("Arrival.mkv")
	makeClip(t, src, "libx264", "eng", "fra")

	before, err := os.Stat(src)
	if err != nil {
		t.Fatal(err)
	}

	// Old enough for the walk's grace period, but the store has never seen it
	// before. On this server that is not evidence of anything: a share-to-
	// share move preserves the mtime, so an "old" file can still be arriving.
	h.advance(2 * minAge)
	sum := h.pass(Options{Mode: ModeRun})

	out := sum.find(t, "Arrival.mkv")
	if out.Waiting == "" {
		t.Fatal("a file seen for the first time was treated as eligible")
	}
	if out.Queued || out.Result != nil {
		t.Fatal("work was done on a file that had only been seen once")
	}
	after, _ := os.Stat(src)
	if after.Size() != before.Size() {
		t.Fatal("the file was modified")
	}

	// A later scan finds it exactly as before, which is the evidence that was
	// missing.
	h.advance(2 * minAge)
	sum = h.pass(Options{Mode: ModeRun})

	out = sum.find(t, "Arrival.mkv")
	if out.Waiting != "" {
		t.Fatalf("still waiting after a second unchanged sighting: %s", out.Waiting)
	}
	if out.Err != nil {
		t.Fatalf("run failed: %v", out.Err)
	}
	if out.Result == nil || !out.Result.Replaced {
		t.Fatal("the settled file was not replaced")
	}
}

func TestASuccessfulRunIsRecordedAndTheFileIsForgotten(t *testing.T) {
	ctx := context.Background()
	h := newHarness(t)
	src := h.path("Blade Runner (1982).mkv")
	makeClip(t, src, "libx264", "eng", "fra")

	h.settle()
	sum := h.pass(Options{Mode: ModeRun})

	out := sum.find(t, "Blade Runner (1982).mkv")
	if out.Err != nil {
		t.Fatalf("run failed: %v", out.Err)
	}
	if out.Plan.Action != decide.ActionRemux {
		t.Fatalf("action = %s, want remux", out.Plan.Action)
	}

	jobs, err := h.store.RecentJobs(ctx, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(jobs) != 1 {
		t.Fatalf("%d jobs recorded, want 1", len(jobs))
	}
	j := jobs[0]
	if j.Status != store.StatusDone {
		t.Errorf("status = %q: %s", j.Status, j.Error)
	}
	if j.Library != "movies" || j.Profile != "standard" || j.Action != decide.ActionRemux {
		t.Errorf("history row = %+v", j)
	}
	if j.SizeBefore == 0 || j.SizeAfter == 0 {
		t.Errorf("sizes not recorded: before %d after %d", j.SizeBefore, j.SizeAfter)
	}

	// The bytes at that path are new, so every cached answer about them is
	// about a file that no longer exists.
	states, err := h.store.Lookup(ctx, []string{src})
	if err != nil {
		t.Fatal(err)
	}
	if len(states) != 0 {
		t.Error("the replaced file kept its old row, so the next scan would trust a stale decision")
	}
}

func TestASettledLibraryIsNotProbedAgain(t *testing.T) {
	h := newHarness(t)
	// Already exactly as the profile wants it: HEVC, one English track.
	makeClip(t, h.path("Dune (2021).mkv"), "libx265", "eng")

	// The first scan only records the sighting. Probing a file that may still
	// be arriving would cache an answer about bytes that are about to change.
	h.advance(2 * minAge)
	h.pass(Options{Mode: ModeScan})
	if got := h.probeCount(); got != 0 {
		t.Fatalf("the first scan probed %d times; nothing has settled yet", got)
	}

	h.advance(2 * minAge)
	h.pass(Options{Mode: ModeScan})
	if got := h.probeCount(); got != 1 {
		t.Fatalf("the settling scan probed %d times, want 1", got)
	}

	h.advance(2 * minAge)
	h.resetProbeCount()
	sum := h.pass(Options{Mode: ModeScan})

	// This is what the decision cache is for. A library of 20,000 files is
	// mostly files that need nothing, and re-probing all of them every three
	// hours is the bulk of the work a scan would otherwise do.
	if got := h.probeCount(); got != 0 {
		t.Errorf("an unchanged, already-conforming file was probed %d more times", got)
	}
	out := sum.find(t, "Dune (2021).mkv")
	if !out.FromCache {
		t.Error("want the decision to have come from the cache")
	}
	if out.Plan.Action != decide.ActionNone {
		t.Errorf("cached action = %s, want none", out.Plan.Action)
	}
}

func TestEditingTheProfileInvalidatesEveryCachedDecision(t *testing.T) {
	h := newHarness(t)
	makeClip(t, h.path("Dune (2021).mkv"), "libx265", "eng")

	h.advance(2 * minAge)
	h.pass(Options{Mode: ModeScan})
	h.advance(2 * minAge)
	h.pass(Options{Mode: ModeScan})

	// Somebody edits the bitrate floor in config.yaml. If the cache did not
	// notice, the change would appear to do nothing at all -- the worst kind
	// of bug, because it looks like the tool working.
	h.profile.Video.Bitrate.FloorKbps = 500
	h.advance(2 * minAge)
	h.resetProbeCount()
	sum := h.pass(Options{Mode: ModeScan})

	if got := h.probeCount(); got != 1 {
		t.Errorf("the file was probed %d times after the profile changed, want 1", got)
	}
	if sum.find(t, "Dune (2021).mkv").FromCache {
		t.Error("a decision made under the old profile was reused")
	}
}

func TestAChangedFileIsLookedAtAgainFromScratch(t *testing.T) {
	h := newHarness(t)
	src := h.path("Upgraded.mkv")
	makeClip(t, src, "libx265", "eng")

	h.settle()
	h.pass(Options{Mode: ModeScan})

	// An *arr stack replaces the file with a better release.
	makeClip(t, src, "libx265", "eng", "fra")
	h.advance(2 * minAge)
	h.resetProbeCount()
	sum := h.pass(Options{Mode: ModeScan})

	out := sum.find(t, "Upgraded.mkv")
	if out.FromCache {
		t.Error("the decision for the previous file was reused for the new one")
	}
	if out.Waiting == "" {
		t.Error("a file that just changed must go back to waiting for it to settle")
	}
	if got := h.probeCount(); got != 0 {
		t.Errorf("a file that just changed was probed %d times before settling", got)
	}

	// Once it has settled again it is looked at from scratch.
	h.advance(2 * minAge)
	sum = h.pass(Options{Mode: ModeScan})
	if got := h.probeCount(); got != 1 {
		t.Errorf("the new file was probed %d times, want 1", got)
	}
	if sum.find(t, "Upgraded.mkv").Plan.Action != decide.ActionRemux {
		t.Error("the new file's extra audio track was not noticed")
	}
}

func TestAFailedFileBacksOffInsteadOfFailingEveryScan(t *testing.T) {
	ctx := context.Background()
	h := newHarness(t)
	src := h.path("Broken.mkv")
	makeClip(t, src, "libx264", "eng", "fra")

	h.runner.Encoder.Binary = script(t, "ffmpeg-failing", "echo 'Invalid data found' >&2\nexit 1\n")

	h.settle()
	sum := h.pass(Options{Mode: ModeRun})

	out := sum.find(t, "Broken.mkv")
	if out.Err == nil {
		t.Fatal("want the failure reported")
	}
	if _, err := os.Stat(src); err != nil {
		t.Fatalf("the original did not survive a failed encode: %v", err)
	}

	jobs, _ := h.store.RecentJobs(ctx, 10)
	if len(jobs) != 1 || jobs[0].Status != store.StatusFailed {
		t.Fatalf("the failure was not recorded: %+v", jobs)
	}
	if !strings.Contains(jobs[0].FFmpegTail, "Invalid data") {
		t.Errorf("ffmpeg's own words were not kept: %q", jobs[0].FFmpegTail)
	}

	// The next scan, half an hour later, leaves it alone. Without this an
	// unattended run repeats the same failure a few thousand times and the
	// report becomes unreadable.
	h.advance(30 * time.Minute)
	h.resetProbeCount()
	sum = h.pass(Options{Mode: ModeRun})

	out = sum.find(t, "Broken.mkv")
	if out.Waiting == "" {
		t.Error("a file that just failed was tried again immediately")
	}
	if h.probeCount() != 0 {
		t.Error("a backed-off file was probed again")
	}

	// Once the backoff expires it is tried again on its own: the tool must
	// never need a nudge to make progress.
	h.advance(2 * time.Hour)
	sum = h.pass(Options{Mode: ModeRun})
	if sum.find(t, "Broken.mkv").Err == nil {
		t.Error("the file was not retried after the backoff expired")
	}
}

func TestRetryFailedGetsPastTheBackoff(t *testing.T) {
	h := newHarness(t)
	src := h.path("Broken.mkv")
	makeClip(t, src, "libx264", "eng", "fra")

	h.runner.Encoder.Binary = script(t, "ffmpeg-failing", "exit 1\n")
	h.settle()
	h.pass(Options{Mode: ModeRun})

	// The cause is understood and fixed; ffmpeg works again.
	h.runner.Encoder.Binary = ""
	h.advance(time.Minute)
	sum := h.pass(Options{Mode: ModeRun, RetryFailed: true})

	out := sum.find(t, "Broken.mkv")
	if out.Waiting != "" {
		t.Fatalf("-retry-failed did not get past the backoff: %s", out.Waiting)
	}
	if out.Err != nil {
		t.Fatalf("the retry failed: %v", out.Err)
	}
	if out.Result == nil || !out.Result.Replaced {
		t.Fatal("the retry did not replace the file")
	}
}

func TestNamingAPathSkipsTheSettleCheck(t *testing.T) {
	h := newHarness(t)
	src := h.path("Named.mkv")
	makeClip(t, src, "libx264", "eng", "fra")

	h.advance(2 * minAge)
	h.runner.Scan.Now = h.now
	h.runner.Now = func() time.Time { return h.now }

	// Somebody typed this path. They know the file is there and are not
	// waiting for it to finish arriving.
	sum, err := h.runner.Pass(context.Background(), Target{
		Label: src, Roots: []string{src}, Profile: h.profile, Named: true,
	}, Options{Mode: ModeRun, Workers: queue.Workers{Remux: 1, Encode: 1}, ProbeWorkers: 1})
	if err != nil {
		t.Fatalf("Pass: %v", err)
	}

	out := sum.find(t, "Named.mkv")
	if out.Waiting != "" {
		t.Fatalf("a named path was held back: %s", out.Waiting)
	}
	if out.Result == nil || !out.Result.Replaced {
		t.Fatal("the named file was not worked on")
	}
}

func TestLimitStopsQueueingButStillReportsTheRest(t *testing.T) {
	h := newHarness(t)
	for _, name := range []string{"a.mkv", "b.mkv", "c.mkv"} {
		makeClip(t, h.path(name), "libx264", "eng", "fra")
	}

	h.settle()
	sum := h.pass(Options{Mode: ModeRun, Limit: 1})

	if !sum.StoppedAtLimit {
		t.Error("want the summary to say it stopped at the limit")
	}
	queued, worked := 0, 0
	for _, o := range sum.Outcomes {
		if o.Queued {
			queued++
		}
		if o.Result != nil {
			worked++
		}
	}
	if queued != 1 || worked != 1 {
		t.Errorf("%d queued and %d worked, want 1 of each", queued, worked)
	}
	if len(sum.Outcomes) != 3 {
		t.Errorf("%d files reported, want all 3 -- the limit caps the work, not the report", len(sum.Outcomes))
	}
}

func TestRemuxesAndEncodesGoToDifferentPools(t *testing.T) {
	h := newHarness(t)
	h.profile.Video.Encoder = "libx265"
	h.profile.Video.Bitrate.FloorKbps = 0

	makeClip(t, h.path("needs-encoding.mkv"), "libx264", "eng")
	makeClip(t, h.path("needs-remuxing.mkv"), "libx265", "eng", "fra")

	h.settle()
	sum := h.pass(Options{Mode: ModeRun})

	if got := sum.find(t, "needs-encoding.mkv").Plan.Action; got != decide.ActionEncode {
		t.Errorf("needs-encoding.mkv: action = %s, want encode", got)
	}
	if got := sum.find(t, "needs-remuxing.mkv").Plan.Action; got != decide.ActionRemux {
		t.Errorf("needs-remuxing.mkv: action = %s, want remux", got)
	}
	if got := sum.Queue.Count(queue.KindEncode); got != 1 {
		t.Errorf("%d items in the encode pool, want 1", got)
	}
	if got := sum.Queue.Count(queue.KindRemux); got != 1 {
		t.Errorf("%d items in the remux pool, want 1", got)
	}
	for _, o := range sum.Outcomes {
		if o.Err != nil {
			t.Errorf("%s: %v", filepath.Base(o.Path), o.Err)
		}
		if o.Result == nil || !o.Result.Replaced {
			t.Errorf("%s was not replaced", filepath.Base(o.Path))
		}
	}
}

func TestSweepForgetsDeletedFilesButNotWhenTheWalkFailed(t *testing.T) {
	ctx := context.Background()
	h := newHarness(t)
	makeClip(t, h.path("kept.mkv"), "libx265", "eng")
	makeClip(t, h.path("deleted.mkv"), "libx265", "eng")

	h.advance(2 * minAge)
	h.pass(Options{Mode: ModeScan, Sweep: true})

	if err := os.Remove(h.path("deleted.mkv")); err != nil {
		t.Fatal(err)
	}
	h.advance(2 * minAge)
	sum := h.pass(Options{Mode: ModeScan, Sweep: true})

	if sum.Swept != 1 {
		t.Errorf("swept %d rows, want 1", sum.Swept)
	}
	states, err := h.store.Lookup(ctx, []string{h.path("kept.mkv"), h.path("deleted.mkv")})
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := states[h.path("kept.mkv")]; !ok {
		t.Error("sweep removed a file that is still there")
	}
	if _, ok := states[h.path("deleted.mkv")]; ok {
		t.Error("sweep left a row for a file that is gone")
	}

	// A root that cannot be read looks exactly like a library somebody
	// deleted. Forgetting 20,000 files because a mount blinked would mean
	// re-probing all of them and waiting two more scans for any to settle.
	h.advance(2 * minAge)
	h.runner.Scan.Now = h.now
	h.runner.Now = func() time.Time { return h.now }
	sum, err = h.runner.Pass(ctx, Target{
		Label:   "library movies",
		Library: "movies",
		Roots:   []string{h.dir, filepath.Join(h.dir, "no-such-mount")},
		Profile: h.profile,
	}, Options{Mode: ModeScan, Sweep: true, ProbeWorkers: 1})
	if err != nil {
		t.Fatalf("Pass: %v", err)
	}
	if len(sum.WalkErrors) == 0 {
		t.Fatal("expected the unreadable root to be reported")
	}
	if sum.Swept != 0 {
		t.Errorf("swept %d rows despite a root failing to read", sum.Swept)
	}
}

func TestAnUnreadableFileIsAFailureAndTheRestOfTheLibraryStillRuns(t *testing.T) {
	h := newHarness(t)
	makeClip(t, h.path("good.mkv"), "libx264", "eng", "fra")
	if err := os.WriteFile(h.path("not-media.mkv"), []byte("this is not a video"), 0o644); err != nil {
		t.Fatal(err)
	}

	h.settle()
	sum := h.pass(Options{Mode: ModeRun})

	if sum.Failures() != 1 {
		t.Errorf("%d failures, want 1", sum.Failures())
	}
	if sum.find(t, "not-media.mkv").Err == nil {
		t.Error("a file ffprobe cannot read must be a failure")
	}
	good := sum.find(t, "good.mkv")
	if good.Err != nil || good.Result == nil || !good.Result.Replaced {
		t.Error("one unreadable file stopped the rest of the library")
	}
}

func TestEventsDescribeThePass(t *testing.T) {
	h := newHarness(t)
	makeClip(t, h.path("film.mkv"), "libx264", "eng", "fra")

	var mu sync.Mutex
	phases := map[Phase]int{}
	h.runner.OnEvent = func(e Event) {
		mu.Lock()
		defer mu.Unlock()
		phases[e.Phase]++
	}

	h.settle()
	h.pass(Options{Mode: ModeRun})

	mu.Lock()
	defer mu.Unlock()
	for _, want := range []Phase{PhaseWalked, PhaseProbe, PhaseQueued, PhaseStart, PhaseDone} {
		if phases[want] == 0 {
			t.Errorf("no %s event was emitted", want)
		}
	}
}

func TestAnUnreadableFileBacksOffLikeAFailedEncode(t *testing.T) {
	h := newHarness(t)
	makeClip(t, h.path("good.mkv"), "libx265", "eng")
	if err := os.WriteFile(h.path("not-media.mkv"), []byte("this is not a video"), 0o644); err != nil {
		t.Fatal(err)
	}

	h.settle()
	sum := h.pass(Options{Mode: ModeRun})
	if sum.Failures() != 1 {
		t.Fatalf("%d failures on the first look, want 1", sum.Failures())
	}

	// A file ffprobe cannot read will not become readable by itself. Without
	// a backoff, every scan for the next six months reports the same failure
	// and exits non-zero, which trains you to ignore the exit status.
	h.advance(10 * time.Minute)
	h.resetProbeCount()
	sum = h.pass(Options{Mode: ModeRun})

	if sum.Failures() != 0 {
		t.Errorf("the same unreadable file failed again immediately (%d failures)", sum.Failures())
	}
	if got := h.probeCount(); got != 0 {
		t.Errorf("the unreadable file was probed %d more times", got)
	}
	if sum.find(t, "not-media.mkv").Waiting == "" {
		t.Error("want the unreadable file reported as backed off rather than silently gone")
	}
}

// A note means a safety rule overrode the configuration, and the row that
// recorded it is deleted the moment the file is replaced. So the note has to
// be copied onto the job, or the cases where a rule actually fired on work
// that happened are exactly the ones that vanish from the history.
func TestASafetyNoteSurvivesTheFileBeingReplaced(t *testing.T) {
	ctx := context.Background()
	h := newHarness(t)
	src := h.path("Only One Track.mkv")
	// A single audio track in a language the profile does not keep, and a
	// floor low enough that the file is worth re-encoding -- so the note is
	// recorded on work that actually happens.
	h.profile.Video.Encoder = "libx265"
	h.profile.Video.Bitrate.FloorKbps = 0
	makeClip(t, src, "libx264", "chi")

	h.settle()
	out := h.pass(Options{Mode: ModeRun}).find(t, "Only One Track.mkv")
	if out.Err != nil {
		t.Fatalf("run failed: %v", out.Err)
	}
	if len(out.Plan.Notes) == 0 {
		t.Fatalf("the plan recorded no note for a file whose only audio track is unwanted")
	}

	jobs, err := h.store.RecentJobs(ctx, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(jobs) != 1 {
		t.Fatalf("%d jobs recorded, want 1", len(jobs))
	}
	if len(jobs[0].Notes) == 0 {
		t.Fatal("the job kept no note, so the history cannot say a rule overrode the config")
	}
	if jobs[0].Notes[0] != out.Plan.Notes[0] {
		t.Errorf("job note = %q, want the plan's note %q", jobs[0].Notes[0], out.Plan.Notes[0])
	}
}
